### PR TITLE
Fix time issues, choose end date or duration, custom colors per event, calendar matches user locale

### LINKED ISSUE #6: end field not working
@glutamate I'm not sure how this time conversion you have works, but all of the events are being displayed on the calendar with end: null. I think there's something wrong with addSeconds

### PR DESCRIPTION
**Pull request by kevin8181**
fixed duration bug- a variable was swapped which made it always return nothing and use the default duration set by fullcalendar
can now use duration or provide another date field for the end time/date.
added field to specify colors per-event
detects user locale and adjusts calendar accordingly

started trying to add editing from the calendar (eg. drag an event to another date and it updates the db) but couldn't figure out how. commented it out and will return to it later.

fixes #6

### CODE REVIEW

**Comment by kevin8181** [comment]
Screenshot from 2022-03-03 14-58-27

Screenshot from 2022-03-06 12-14-29

**Comment by kevin8181** [comment]
also added date range selection- drag to highlight an area on the calendar and it will open an edit view with the start and end date filled. doesn't support duration yet

**Comment by kevin8181** [comment]
fixes #6

**Comment by kevin8181** [comment]
@glutamate

**Comment by glutamate** [comment]
thanks @kevin8181. For help with editing have a look at my yet to be released gantt Chart https://github.com/saltcorn/svelte-gantt. If it is still not clear I can help with this.

You need to define a route inside the view https://github.com/saltcorn/svelte-gantt/blob/main/index.js#L351

for implementation e.g. https://github.com/saltcorn/svelte-gantt/blob/main/index.js#L296-L334

**Pull request merged**
